import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface PatientData {
  name: string;
  age?: number;
  gender?: string;
  height?: number;
  weight?: number;
  assignedDoctor?: string;
}

interface MedicationItem {
  type: string;
  medicine: string;
  dosage: string;
  frequency: string;
  timing: string[];
}

export const generatePatientReport = (
  patient: PatientData,
  medications: { modern: MedicationItem[]; ayurvedic: MedicationItem[] },
  title: string = "Patient Interaction Report"
) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(40, 40, 40);
  doc.text("Suraksha Setu", 14, 22);
  
  doc.setFontSize(14);
  doc.setTextColor(100, 100, 100);
  doc.text(title, 14, 30);
  
  // Patient Details
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Patient Name: ${patient.name || "N/A"}`, 14, 45);
  doc.text(`Age/Gender: ${patient.age || "N/A"} / ${patient.gender || "N/A"}`, 14, 52);
  doc.text(`Height/Weight: ${patient.height ? patient.height + "cm" : "N/A"} / ${patient.weight ? patient.weight + "kg" : "N/A"}`, 14, 59);
  doc.text(`Doctor: ${patient.assignedDoctor || "N/A"}`, 14, 66);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 73);
  
  let currentY = 85;

  const prepareTableData = (meds: MedicationItem[]) => {
    return meds.map(m => [
      m.medicine,
      m.dosage,
      m.frequency,
      m.timing.join(", ")
    ]);
  };
  
  // Modern Medicines Table
  if (medications.modern && medications.modern.length > 0) {
    doc.setFontSize(14);
    doc.text("Modern Medicines", 14, currentY);
    
    autoTable(doc, {
      startY: currentY + 5,
      head: [["Medicine", "Dosage", "Frequency", "Timing"]],
      body: prepareTableData(medications.modern),
      theme: "grid",
      headStyles: { fillColor: [14, 165, 233], textColor: 255 }, // Theme primary color
      styles: { fontSize: 10 }
    });
    // @ts-ignore
    currentY = doc.lastAutoTable.finalY + 15;
  }
  
  // Ayurvedic Medicines Table
  if (medications.ayurvedic && medications.ayurvedic.length > 0) {
    doc.setFontSize(14);
    doc.text("Ayurvedic Formulations", 14, currentY);
    
    autoTable(doc, {
      startY: currentY + 5,
      head: [["Medicine", "Dosage", "Frequency", "Timing"]],
      body: prepareTableData(medications.ayurvedic),
      theme: "grid",
      headStyles: { fillColor: [16, 185, 129], textColor: 255 }, // Theme safe color (emerald)
      styles: { fontSize: 10 }
    });
    // @ts-ignore
    currentY = doc.lastAutoTable.finalY + 15;
  }

  // Add footer
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  // @ts-ignore
  const pageHeight = doc.internal.pageSize.height || doc.internal.pageSize.getHeight();
  doc.text("This report is generated by Suraksha Setu.", 14, pageHeight - 10);
  
  // Save PDF
  doc.save(`${patient.name.replace(/\s+/g, "_")}_Report.pdf`);
};

export const generateHistoryReport = (
  history: Array<{ date: string; drug: string; herb: string; result: string; by: string }>,
  title: string = "Interaction History Report"
) => {
  const doc = new jsPDF();
  
  doc.setFontSize(20);
  doc.text("Suraksha Setu", 14, 22);
  
  doc.setFontSize(14);
  doc.text(title, 14, 30);
  
  const prepareTableData = () => {
    return history.map(h => [
      h.date,
      h.drug,
      h.herb,
      h.result.toUpperCase(),
      h.by
    ]);
  };
  
  if (history.length > 0) {
    autoTable(doc, {
      startY: 40,
      head: [["Date", "Modern Drug", "Ayurvedic", "Result", "Checked By"]],
      body: prepareTableData(),
      theme: "grid",
      headStyles: { fillColor: [14, 165, 233], textColor: 255 },
      styles: { fontSize: 10 }
    });
  } else {
    doc.setFontSize(12);
    doc.text("No history available.", 14, 40);
  }
  
  const pageHeight = doc.internal.pageSize.height || doc.internal.pageSize.getHeight();
  doc.setFontSize(10);
  doc.text("This report is generated by Suraksha Setu.", 14, pageHeight - 10);
  
  doc.save("Interaction_History_Report.pdf");
};
